<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('consumer', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('consumerId'));
echo $this->formRow($form->get('groupId'));
echo $this->formRow($form->get('login'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('expirationDateAndTime'));
echo $this->formRow($form->get('imageExtention'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();